build:
  environment:
    image: default-bionic
    php:
      version: 8.3
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths: [src/*, tests/*]
