name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  # Every Friday at 10:20am UTC
  schedule:
    - cron: '20 10 * * 5'

jobs:
  ci:
    name: CI
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'lekoala') || (github.event_name != 'schedule')
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
